name: Check requirement to update E2E test suite
on:
  pull_request:
    types: [ opened, synchronize, edited ]
    paths:
      - 'bundle/**'
      - 'config/**'
      - 'Dockerfiles/**'
      - 'internal/**'
      - 'pkg/**'
      - 'cmd/main.go'

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  check-e2e-update-requirement:
    name: Check requirement to update E2E test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check requirement to update E2E test suite
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;

            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            const prBody = pr.body || '';
            const skipE2eChecked = /- \[x\]\s*Skip requirement to update E2E test suite for this PR/i.test(prBody);
            
            console.log(`Skip e2e checkbox checked: ${skipE2eChecked}`);
            
            if (skipE2eChecked) {
              console.log('Skip e2e checkbox is checked, looking for justification comment...');
              
              const { data: comments } = await github.rest.issues.listComments({
                owner,
                repo,
                issue_number: prNumber,
              });
              
              // Look for a comment from the PR author that contains justification
              const authorComments = comments.filter(comment => 
                comment.user.login === pr.user.login &&
                (comment.body.includes('## E2E update requirement opt-out justification:'))
              );
              
              if (authorComments.length === 0) {
                // No justification comment from the PR author found
                // bot hasn't posted about it yet => have it post a comment
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: `## ❌ E2E Update Requirement Check Failed
            
            You have checked the "Skip requirement to update E2E test suite for this PR" checkbox, but no justification comment by the PR author was found.
            
            **Action required from the PR author:**
            1. Please add a comment to this PR explaining why e2e tests are not needed for this change.
            - the skip justification comment is **required** to start with \`## E2E update requirement opt-out justification:\` title, and include a short summary of reasons for opting-out of this requirement
            2. To re-trigger the check after adding the justification comment, you can edit the PR description in a non-disruptive way (e.g. by adding a new line at the end)`
                });
                
                core.setFailed('❌ FAILURE: PR author opted-out of the E2E test suite update requirement, but no justification comment was found');
                return;
              } else {
                console.log(`Found justification comment from PR author`);
                console.log('✅ SUCCESS: PR author opted-out of the E2E test suite update requirement and provided a justification comment');
              }
            } else {
              // skip e2e update requirement checkbox is not checked
              // => verify e2e tests were added/updated
              console.log('Requirement to update E2E test suite was is not set to be skipped, checking for e2e test updates in the PR...');
              
              const { data: files } = await github.rest.pulls.listFiles({
                owner,
                repo,
                pull_number: prNumber,
              });
              
              // Check if any files in tests/e2e directory were modified
              const e2eFilesModified = files.some(file => 
                file.filename.startsWith('tests/e2e/') && 
                (file.status === 'added' || file.status === 'modified')
              );
              
              console.log(`E2E files modified: ${e2eFilesModified}`);
              console.log('Modified files:', files.map(f => f.filename).join(', '));
              
              if (!e2eFilesModified) {
                // Check if bot already posted a comment about missing e2e tests
                const { data: comments } = await github.rest.issues.listComments({
                  owner,
                  repo,
                  issue_number: prNumber,
                });

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: `## ❌ E2E Update Requirement Check Failed
            
            No e2e tests were added/updated as part of this PR.
            
            **Action required from the PR author:** Please either:
            1. Add or update e2e tests relevant to the PR changes in the \`tests/e2e/\` directory, OR
            2. Check the "Skip requirement to update E2E test suite" checkbox in the PR template and provide a justification comment explaining why e2e tests are not needed for this change. The skip justification comment is required to start with \`## E2E update requirement opt-out justification:\` title, and include a short summary of reasons for opting-out of this requirement
            
            **Why this check exists:**
            - E2E tests help ensure that changes work correctly in a real environment and don't break existing functionality
            - by default, every code-related PR should include an extension/update to the E2E test suite to cover the new changes
            - if the PR author is in doubt whether this requirement is applicable for their PR, please refer to the PR template for guidance about appropriate/inappropriate cases for opting-out`
                });
                
                core.setFailed('❌ FAILURE: No e2e tests updated and skip checkbox not checked');
                return;
              } else {
                console.log('✅ SUCCESS: E2E tests were added/updated in the PR');
              }
            }
            
            console.log('✅ SUCCESS: E2E requirement check passed');
