name: Build Catalog FBC and run Integration tests
on:
  pull_request_target:
    # action steps require 'run-integration-tests' label to be present, otherwise it's skipped
    types: [ labeled ]
    paths:
      - 'bundle/**'
      - 'cmd/**'
      - 'config/**'
      - 'Dockerfiles/**'
      - 'internal/**'
      - 'pkg/**'
      - 'cmd/main.go'

permissions: { }

jobs:
  build-and-push-images:
    name: Build Catalog FBC and run Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Build and push images
        uses: ./.github/workflows/utils/image-build-push.yaml
        if: ${{ github.event.label.name == 'run-integration-tests' }}

      - name: Report image build success and give further instructions
        if: ${{ github.event.label.name == 'run-integration-tests' }}
        run: |
          echo "Catalog image built and pushed successfully!"
          echo "** Dependent action will be triggered, please await GitHub Bot to comment '/test-integration' on the PR. **"
          echo "This comment will trigger the integration test run."
