name: Integration tests - build images
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'Makefile'
      - 'OWNERS'
      - 'OWNERS_ALIASES'
      - 'PROJECT'

env:
  IMAGE_TAG_BASE: quay.io/${{ secrets.QUAY_ORG }}/opendatahub-operator
  TAG: pr-${{ github.event.number }}
  IMAGES_ZIP: operator_images.zip
  TAG_VARS_FILE: tag_vars.txt
jobs:
  validate-and-build:
    name: Validate user and build images
    runs-on: ubuntu-latest
    env:
      IMAGE_BUILDER: podman
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Verify PR author and fork repo
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          FORK_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        shell: bash
        run: |
          set -e
          python ./.github/scripts/verify_pr_author.py

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build operator image
        env:
          IMG: ${{ env.IMAGE_TAG_BASE }}:${{ env.TAG }}
        run:
          make image-build

      - name: Get latest release version
        env:
          OPERATOR_REPOSITORY_NAME: opendatahub-io/opendatahub-operator
        run: |
          version_tag=$(curl -s https://api.github.com/repos/${OPERATOR_REPOSITORY_NAME}/releases/latest | jq -r .tag_name)-${{ env.TAG }}
          echo "VERSION_TAG=$version_tag" >> $GITHUB_ENV

      - name: Build bundle image
        env:
          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:${VERSION_TAG}
        run:
          make bundle-build

      - name: Podman save
        env:
          IMG: ${{ env.IMAGE_TAG_BASE }}:${{ env.TAG }}
          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:${VERSION_TAG}
        run:
          podman save --output ${{ env.IMAGES_ZIP }} ${{ env.IMG }} ${{ env.BUNDLE_IMG }}

      - name: Save tag variables
        run: |
          echo $TAG >> ${{ env.TAG_VARS_FILE }}
          echo $VERSION_TAG >> ${{ env.TAG_VARS_FILE }}
          

      - name: Upload images as GitHub artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: operator-images
          path: |
            ./${{ env.IMAGES_ZIP }}
            ./${{ env.TAG_VARS_FILE }}
          retention-days: 1
