name: Manage integration test label on PR
on:
  issue_comment:
    types: [ created ]

permissions:
  pull-requests: write

jobs:
  manage-integration-test-label:
    name: Manage integration test label on PR
    if: |
      github.event.issue.pull_request &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
      - name: Add integration test label
        if: contains(github.event.comment.body, '/add-label-test-integration')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['run-integration-tests']
            })

      - name: Remove integration test label on PR
        if: contains(github.event.comment.body, '/remove-label-test-integration')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'run-integration-tests'
            })
