name: Post integration tests trigger comment
on:
  workflow_run:
    workflows: ["Build Catalog FBC and run Integration tests"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  post-comment-to-trigger-tests:
    name: Post comment to trigger tests
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Post integration tests trigger comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = ${{ github.event.workflow_run.pull_requests[0].number }};
              
            const body = "/test-integration";
              
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });